name: "myapp_react"
services:
  react:
    container_name: myapp_react
    build: .
    environment:
      - ./env/react.env
    ports:
      - "5173:5173"
    networks:
      - myapp_network
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  myapp_network:
    driver: bridge
